[info]
name = "continue_in_closure_argument"
discription = "Putting a continue inside the arguments of a closure results in an ICE"
discovery_date = 2018-06-22T13:22:47+00:00
type = "ICE"
effected_versions = [ "rustc 1.27.0 (3eda71b00 2018-06-19)", "rustc 1.28.0-beta.2 (5981061e5 2018-06-22)", "rustc 1.28.0-nightly (60efbdead 2018-06-23)",]

[resolved]
stable = false
beta = false
nightly = false

[issue]
link = "https://github.com/rust-lang/rust/issues/51708"

[optional]
last_checked = 2018-06-26T12:59:50+00:00

[additional]
