[info]
name = "break_in_closure_argument"
discription = "putting a break in the argument of a closure results in an ICE"
discovery_date = 2018-06-22T13:49:47+00:00
type = "ICE"
effected_versions = [ "rustc 1.27.0 (3eda71b00 2018-06-19)", "rustc 1.28.0-beta.3 (14a78df65 2018-06-25)", "rustc 1.28.0-nightly (2a1c4eec4 2018-06-25)",]

[resolved]
stable = false
beta = false
nightly = false

[issue]
link = "https://github.com/rust-lang/rust/issues/51707"

[optional]
last_checked = 2018-06-26T13:27:05+00:00

[additional]
