[info]
name = "break_labeled_while"
discription = "Breaking a labeled while loop in the condition of the loop caused an illigal instruction"
discovery_date = 2018-05-18T19:47:36+00:00
type = "Invalid code generation"
effected_versions = [ "rustc 1.27.0 (3eda71b00 2018-06-19)",]

[resolved]
stable = false
beta = true
nightly = true

[issue]
link = "https://github.com/rust-lang/rust/issues/50856"

[optional]
last_checked = 2018-06-23T19:54:48+00:00

[additional]
