[info]
name = "break_labeled_while_in_const_expr"
discription = "breaking a labeled while loop in a constant context results in an ICE"
discovery_date = 2018-05-30T17:34:38+00:00
type = "ICE"
effected_versions = [ "rustc 1.27.0 (3eda71b00 2018-06-19)", "rustc 1.28.0-beta.6 (915ac6602 2018-06-30)", "rustc 1.28.0-nightly (e3bf634e0 2018-06-28)",]

[resolved]
stable = false
beta = false
nightly = false

[issue]
link = "https://github.com/rust-lang/rust/issues/51350"

[optional]
last_checked = 2018-07-01T19:26:51+00:00

[additional]
